blankIndexSuccess:
  has_layout: no
  
indexSuccess:
  javascripts: [jquery.chained.mini.js]
  components:
    kwWebTrekk:   [kw, webtrekk_home]

sottoscrizionePremiumDemoSuccess:
  metas:
    title:        "Adesione al servizio Premium - OpenParlamento"

graficoDistanzeSuccess:
  javascripts:    [<?php echo sfConfig::get('sf_js_google_load')=='true'?'https://ajax.googleapis.com/ajax/libs/swfobject/2.1/swfobject.js':'fe/swfobject.js'?>]

getLoggedUserSuccess:
  has_layout:     off
  http_metas:
      content-type: "text"
