<?php

class nahoWikiConfigHandler extends sfYamlConfigHandler
{
  
  const GLOBAL_PREFIX = 'app_nahoWikiPlugin';
  
  public function execute($config_files)
  {
    // generate prefix
    $first_config_file = basename(reset($config_files));
    $prefix = substr($first_config_file, 0, strpos($first_config_file, '.'));

    // retrieve yaml data
    $config = $this->parseYamls($config_files);

    // get current environment
    $environment = sfConfig::get('sf_environment');

    // merge default and environment specific config
    $main_config = isset($config['all']) ? $config['all'] : array();
    $env_config = isset($config[$environment]) ? $config[$environment] : array();
    $config = sfToolKit::arrayDeepMerge($main_config, $env_config);

    $code = sprintf("<?php\n" .
                    "// auto-generated by nahoWikiConfigHandler\n" .
                    "// date: %s\n" .
                    "sfConfig::set('%s_%s', %s);",
                    date('Y-m-d H:i:s'), self::GLOBAL_PREFIX, $prefix, var_export($config, 1));

    return $code;
  }
}
