# parametri per la connessione al server solr e  sul tipo di query
task:
  query_debug_level: 1

dev:
  query_debug_level: 2

all:
  query_debug_level: 0
  query_handler: dismax
  index_dir: "/var/solr/data/openparlamento18/data/index/"
  connection:
    host: "localhost"
    port: "8983"
    path: "/solr/openparlamento18"
